import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import { MyProvider } from "./components/context";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hinder",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <MyProvider>
      <body className={inter.className}>
        {children}
        <Footer/>
        </body>
      </MyProvider>
    </html>
  );
}
